이화은/myweb/models.py
## 모듈로딩
from myweb import db

class FoodWaste(db.Model) :
    d = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String(20), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

class Trashlist(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String(20),nullable=False)
    create_date = db.Column(db.DateTime, nullable=False)

class recycleTrash(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String(20), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

이화은/myweb/__init__.py
## 모듈 로딩
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

## DB관련 인스턴스 생성 
db = SQLAlchemy() # 전역 변수
migrate = Migrate() # 전역 변수


def create_app() :
    app = Flask(__name__)
    
    # 성정 내용 로딩 (파이선 파일에서 읽어들인다.)
    app.config.from_pyfile('config.py')

    # ORM 즉, DB 초기화 -> db객체를 create_app 안에서 생성하면 블루프린트와 같은 다른 모듈에서 불러올 수 없기 때문에 밖에서 생성.
    db.init_app(app)
    migrate.init_app(app, db)

    from .views import foodmdl

    from .views import main_views
    app.register_blueprint(main_views.bp)

    return app

이화은/myweb/views/foodmdl.py
import joblib
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
import cv2
import os
from torchvision.transforms.functional import to_pil_image

class CNN(nn.Module) :
    def __init__(self) : # 모델의 구조를 정의 후, 초기화
        super().__init__() # 부모 클래스인 nn.Module의 초기화 메서드를 호출
        self.conLayer = nn.Conv2d(in_channels=3, out_channels=25, kernel_size = 3) # 합성곱 레이어1 정의
        self.conLayer2 = nn.Conv2d(in_channels=25, out_channels=16, kernel_size = 3) # 합성곱 레이어2 정의
        self.conLayer3 = nn.Conv2d(in_channels=16, out_channels=10, kernel_size = 3) # 합성곱 레이어3 정의
        
        self.pool = nn.MaxPool2d(2, 2) 
        self.fc1 = nn.Linear(360, 180)
        self.fc2 = nn.Linear(180, 2)

    def forward(self, x) :
        
        x = self.conLayer(x)
        x = F.relu(x)
        x = self.pool(x)
        
        x = self.conLayer2(x)
        x = F.relu(x)
        x = self.pool(x)

        x = self.conLayer3(x)
        x = F.relu(x)
        x = self.pool(x)
        
        x = x.view(-1, 360)
        
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)

        return x
    
def mymdl():
    model_name = '/model.pth'
    # model_path = 'myweb/views/model.pth'
    pklfile = os.path.dirname(__file__) + model_name
    mdl = torch.load(pklfile)
    return mdl

def img_predict(pic_path, mdl) :
    # 이미지 전처리 시 사용
    preprocessing = transforms.Compose(
        [transforms.Resize(size=(64, 64)), # 사이즈 조정 64 * 64
        transforms.ToTensor()]# 텐서로 변환
    )

    testPic = cv2.imread(pic_path)
    test_pil = to_pil_image(testPic)

    if os.path.exists(pic_path) :
        transformed_img = preprocessing(test_pil)
        transformed_img = transformed_img.unsqueeze(0) # 배치 차원을 추가
        
        mdl.eval()
        with torch.no_grad() : # 그래디언트 업데이트 X
            output = mdl(transformed_img) # 전처리된 이미지를 모델에 입력하여 출력을 계산
            _, predicted = torch.max(torch.softmax(output, dim=1).data, 1) # 모델의 출력에 소프트맥스 함수를 적용하여 확률값으로 변환
            result = f"{100*torch.softmax(output, dim=1).data[0][predicted].item():.1f}% 확률로 {'음식물 쓰레기로 분리배출 가능합니다' if predicted.item() else '음식물 쓰레기로 분리배출 할 수 없습니다'}!"
        return result

이화은/myweb/views/main_views.py
from flask import Blueprint, render_template, request
from flask import current_app
from werkzeug.utils import secure_filename
import os
import PIL
import joblib
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
import cv2
import os
from torchvision.transforms.functional import to_pil_image
from .foodmdl import img_predict, CNN
from ..models import FoodWaste
from datetime import datetime
from myweb import db

mdl = CNN()

bp = Blueprint('main',
               __name__,
               template_folder='templates',
               url_prefix = '/')

# 라우팅 함수들
@bp.route('/')
def index() :
    return render_template('input.html')

# 라우팅 함수: 이미지 제출 처리
@bp.route('/classify', methods=['POST'])
def classify():
    try:
        
        file = request.files['img']
        filename = secure_filename(file.filename)

        uploads_dir = os.path.join(current_app.static_folder, 'uploads')
        file_path = os.path.join(uploads_dir, filename)
        print(file_path, filename)

        # Blueprint의 static_folder를 사용하여 파일 저장 경로 생성
        # file_path = os.path.join('static', 'uploads', filename)
        file_path = f'myweb/static/uploads/{filename}'
        file.save(file_path)

        result = img_predict(file_path, mdl)

        col = FoodWaste(type=type, create_date=datetime.now()) # 하나의 행 데이터
        db.session.add(col)     # 행 데이터 추가
        db.session.commit()     # 데이터베이스에 적용. 이걸 해야 server에 적용됨


        # 분류 결과를 result.html에 전달
        return render_template('result.html', filename=filename, result=result)
   
    except Exception as e:

        # 예외 발생 시 오류 메시지 출력
        return f"Error: {str(e)}"

이화은/myweb/templates/input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>myweb</title>
    <link href = "{{url_for('static', filename = 'mystyle.css')}}" rel="stylesheet">
</head>
<body>
    <center>
        <h1>🍏 음식물 쓰레기와 일반 쓰레기 분류 🍏</h1>
    </center>
    <center>
        <form action="{{ url_for('main.classify') }}" method="POST" enctype="multipart/form-data">
            <fieldset>
            <label><h2> Q. 이 과일은 어떻게 버려야 할까요?</h2></label><br>
            <input type="file" name = "img" id = "img" accept=".png, .jpg, .jpeg"><br>
            <input type="submit" value =" " class="submit-button">   
            </fieldset>
        </form>
    </center>
</body>
</html>

이화은/myweb/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>myweb</title>
    <link href = "{{url_for('static', filename = 'mystyle.css')}}" rel="stylesheet">
</head>
<body>
    <center>
        <h1>🍏 음식물 쓰레기와 일반 쓰레기 분류 🍏</h1>
    </center>
    <center>
        <form action = '{{action}}' method="{{method}}" enctype="multipart/form-data">
            <fieldset>
                <label><h2> Q. 이 과일은 어떻게 버려야 할까요?</h2></label>
                <img src="{{ url_for('static', filename='uploads/' + filename) }}" style="max-width: 20%; height: auto;" alt="uploaded image"><br><br>
            <p>
                <h4>{{result}}</h4>
            </p>
        </fieldset>
        </form>
    </center>
</body>
</html>